# Generated by Django 5.1.15 on 2026-09-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=15)),
                ('operateur', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('BANCAIRE', 'Virement bancaire')], max_length=20)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('token_gateway', models.CharField(blank=True, max_length=120)),
                ('url_paiement', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('INITIEE', 'Initiée'), ('EN_ATTENTE', 'En attente'), ('REUSSIE', 'Réussie'), ('ECHOUEE', 'Échouée'), ('ANNULEE', 'Annulée')], default='INITIEE', max_length=20)),
                ('reponse_gateway', models.JSONField(blank=True, default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to=settings.AUTH_USER_MODEL)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='annonces.annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
