# Generated by Django 5.1.15 on 2026-09-15 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('secteur', models.CharField(choices=[('PECHE', 'Pêche'), ('ELEVAGE', 'Élevage'), ('AGRICULTURE', 'Agriculture')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.PositiveIntegerField(help_text='Prix en GNF')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('unite', models.CharField(choices=[('KG', 'Kg'), ('TONNE', 'Tonne'), ('PIECE', 'Pièce'), ('LITRE', 'Litre'), ('SAC', 'Sac'), ('AUTRE', 'Autre')], default='KG', max_length=10)),
                ('localite', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('MODEREE', 'Modérée'), ('VENDU', 'Vendu')], default='ACTIVE', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='annonces.categorie')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
